blank_issues_enabled: false
contact_links:
  - name: ğŸ› Bug Report
    url: https://github.com/UmmItC/Dotfiles/issues/new?template=bug_report.md
    about: Something broken? Report it here
  - name: âœ¨ Feature Request  
    url: https://github.com/UmmItC/Dotfiles/issues/new?template=feature_request.md
    about: Want something new? Ask here 